### ISSUE TITLE
Support VCard 4 group properties

### ISSUE THREAD

**Issue by ScottPeterJohnson** [mstilkerich/rcmcarddav#331]
When syncing, it seems like RCMCardDav can't recognize version 4 vcard group properties (MEMBER, KIND) and only looks for Apple-style properties (X-ADDRESSBOOKSERVER-MEMBER, X-ADDRESSBOOKSERVER-KIND). 
(Also, it seems like X-ADDRESSBOOKSERVER-MEMBER property must have "urn:uuid:" pointing to a vcard UID without the "urn:uuid:" prefix; is that a hack for V3? Probably shouldn't carry over to V4 if so.)

**Comment by mstilkerich** [comment]
Hello Scott,

> When syncing, it seems like RCMCardDav can't recognize version 4 vcard group properties (MEMBER, KIND) and only looks for Apple-style properties (X-ADDRESSBOOKSERVER-MEMBER, X-ADDRESSBOOKSERVER-KIND).

Yes, that is correct. The main reason is that Apple addressbook applications are the only ones I have seen so far that support groups stored in VCards, and they use that extension and won't recognize the v4 properties even when putting v4 cards. I have not seen any v4 KIND=group vCards in the wild so far. Are you aware of an addressbook application that uses them? Additionally, currently rcmcarddav always creates version 3 vCards, because they have the best interoperability with CardDAV servers.

> (Also, it seems like X-ADDRESSBOOKSERVER-MEMBER property must have "urn:uuid:" pointing to a vcard UID without the "urn:uuid:" prefix; is that a hack for V3? Probably shouldn't carry over to V4 if so.)

This is based on what I observed in cards created by Apple using that extension. For example, I just created a new group and contained contact in iCloud Web Addressbook. It produces these cards:

```
BEGIN:VCARD
VERSION:3.0
UID:4115AF7A-8CF2-45F0-A9B1-C109DD78E48A
N:Neu2;iCloud;;;
FN:iCloud Neu2
EMAIL;TYPE=HOME;TYPE=pref;TYPE=INTERNET:neu2@example.com
PRODID:-//Apple Inc.//iCloud Web Address Book 2025B86//EN
REV:2021-01-30T03:47:48Z
END:VCARD

BEGIN:VCARD
VERSION:3.0
UID:5808F716-5899-4C59-BDCC-798988D65279
N:iCloud Gruppe Neu
FN:iCloud Gruppe Neu
X-ADDRESSBOOKSERVER-KIND:group
X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:4115AF7A-8CF2-45F0-A9B1-C109DD78E48A
PRODID:-//Apple Inc.//iCloud Web Address Book 2025B86//EN
REV:2021-01-30T03:47:58Z
END:VCARD
```
As you can see, the `urn:uuid:` is not part of the `UID`. In vCard 4.0, `UID` must be a URI, but in vCard 3 it can be any text value.

In general, I'm open to supporting the vCard 4 attributes. It would probably not be too difficult to interpret the groups on received cards. But when creating or updating cards, a couple of new issues arise:
  * Servers are not required to support v4 vCards and may reject them -> there needs to be intelligence on when to create v4 and when v3 vcards; it can be a user setting, but many users will not know what choice to make
  * vCard 4 allows other values for `MEMBER` besides UID references. These are currently dropped and would have to be preserved.
  * Possibly v4 vcards need to be requested from the server, otherwise a server normally should have to convert a vcard to v3. I am not aware of a server performing such conversion though, most just deliver the card as it was stored.
  * And probably more that will pop up :-)

So it will require some thinking to come up with an interoperable design, and be a bit of work to implement and test, so I would like to have some use case that justifies investing into it, because, as I said, I'm not currently aware of any application actually using the v4 mechanisms to represent groups.

**Comment by ScottPeterJohnson** [comment]
Ah, I see. The "application" actually generating the cards was me using [Ezvcard](https://github.com/mangstadt/ez-vcard) while porting native Roundcube contacts to CardDAV. It sounds like I should just set it to produce V3 CATEGORIES groups instead, since even if you fixed this I'd probably just run into support problems with other clients.

Thanks for the fast response and great plugin!
