### ISSUE TITLE
Release tarball not available

### ISSUE THREAD

**Issue by sdondley** [mstilkerich/rcmcarddav#342]
I'm trying to follow instructions here: https://github.com/mstilkerich/rcmcarddav/blob/master/doc/INSTALL.md

I'm on debian. The release tarball that is linked to on that page results in 404.

So I tried with composer and manually symlinked to plugin from /var/lib/roundcube/plugins

Using that method, I get this error:

```
  thrown in /usr/share/roundcube/plugins/carddav/carddav.php on line 172
[29-Apr-2021 08:08:26 America/New_York] PHP Fatal error:  Uncaught Error: Class 'MStilkerich\CardDavAddressbook4Roundcube\Config' not found in /usr/share/roundcube/plugins/carddav/carddav.php:172
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(99): carddav->init()
#1 /usr/share/roundcube/program/include/rcmail.php(135): rcube_plugin_api->init(Object(rcmail), 'login')
#2 /usr/share/roundcube/program/include/rcmail.php(79): rcmail->startup()
#3 /usr/share/roundcube/index.php(43): rcmail::get_instance(0, NULL)
#4 {main}
  thrown in /usr/share/roundcube/plugins/carddav/carddav.php on line 172
```

Not sure what else to try tat this point.

**Comment by mstilkerich** [comment]
You find the tarballs on the releases page github. 
https://github.com/mstilkerich/rcmcarddav/releases

Thanks for pointing out the broken link in the docs, I will fix it.

**Comment by mstilkerich** [comment]
Concerning the dependency error: As far as I remember, the composer.json resides under /usr/share/roundcube and I guess that is where you ran composer. It would install the dependencies at /usr/share/roundcube/vendor in that case, but roundcube will look at /var/lib/roundcube/vendor. You can do a symlink, but I assume a vendor directory already exists under the var location with packages dependencies. So to use composer, you would better copy composer.json to the var location and run composer there. I also remember that some package names (independent of carddav) needed to be adapted in the packaged composer.json, otherwise you would get errors.

**Comment by sdondley** [comment]
Thanks for the additional help. I know next to nothing about composer and only recently installed it specifically for roundcube. Your memory is correct, the packages are getting installed in /usr/.../vendor and not in /var/.../vendor. I'll play around with this some more when I get a chance.

**Comment by mstilkerich** [comment]
I assume this issue is resolved. If not, please reopen or create a new issue.
