### ISSUE TITLE
dbmigration failed with error

### ISSUE THREAD

**Issue by groinwood** [mstilkerich/rcmcarddav#362]
Hi,
When doing an upgrade from v3 the dbmigration `0012-fixmysqlconstraints/mysql.sql` failed with error 

```
ALTER TABLE carddav_contacts DROP INDEX `uri`, ADD UNIQUE INDEX(uri, abook_id);) failed: [1071] Specified key was too long; max key length is 767 bytes
```

Server: MariaDB
Engine: InnoDB
Collation: utf8mb4_unicode_ci
Character Set: utf8mb4

**Comment by mstilkerich** [comment]
Hmm, I'm a bit confused as to why this happens. In fact, the index was already there before the migration, and the only thing that changes in this migration concerning the `uri`  column is the not-null constraint is added.

The index is composed of the uri column (`varchar(700)`) and the abook_id (`INT`). Because of the used charset, a character can in theory take up to 4 bytes. However, no multi-byte characters should be part of an URL, therefore I think the uri might be up to 700 characters in length. Therefore I have no explanation why the 767 byte limit is exceeded.

- What version of Maria DB are you using? (because I cannot reproduce with mine)
- Does your carddav_contacts actually contain an URL that is 700 characters in length? I am wondering if this is related to your data or a general constraint based on the theoretical maximum length an index key could become. But then the error should occur independently of the data stored in the DB, and in my case the migration works fine.

**Comment by mstilkerich** [comment]
I tried: Even with a 700 character URL the migration works just fine for me.

**Comment by mstilkerich** [comment]
Ok, I think I got it.

- It is indeed a check of the theoretical limits independent of the actual data
- The was a change in the [default format](https://mariadb.com/kb/en/innodb-row-formats-overview/#default-row-format) used to store the database rows from `COMPACT` to `DYNAMIC`. This change happened with MariaDB 10.2.2
- Since you are upgrading from v3 your table probably exists for a long time and my guess is it uses the `COMPACT` format for row storage. In my test cases on the other hand, the tables are created from scratch on every test run, so they use the current default `DYNAMIC`.
- The index prefix limit with `DYNAMIC` is [3072 bytes](https://mariadb.com/kb/en/innodb-dynamic-row-format/#index-prefixes-with-the-dynamic-row-format) when [`innodb_large_prefix`](https://mariadb.com/kb/en/innodb-system-variables/#innodb_large_prefix) is `ON` (which is the default since 10.2.2 as well) and with a [page size of 16 kiB](https://mariadb.com/kb/en/innodb-limitations/#page-sizes), whereas with `COMPACT` it is [767 bytes](https://mariadb.com/kb/en/innodb-compact-row-format/#index-prefixes-with-the-compact-row-format).
- 3072 bytes is sufficient even when assuming a worst-case of 4-bytes storage usage per character.

You can check the row format using the `show table status like '%carddav_%';`. The `Row_format` column for the `carddav_contacts` table shows `Compact` if my guess is right.

You can convert the row_format using the following command:
`ALTER TABLE carddav_contacts ROW_FORMAT=DYNAMIC;` 

Actually I would suggest to do that for all the carddav tables. You can insert these lines at the top of `dbmigrations/0012-fixmysqlconstraints/mysql.sql` and that should fix the issue:
```mysql
ALTER TABLE TABLE_PREFIXcarddav_addressbooks ROW_FORMAT=DYNAMIC;
ALTER TABLE TABLE_PREFIXcarddav_contacts ROW_FORMAT=DYNAMIC;
ALTER TABLE TABLE_PREFIXcarddav_xsubtypes ROW_FORMAT=DYNAMIC;
ALTER TABLE TABLE_PREFIXcarddav_groups ROW_FORMAT=DYNAMIC;
ALTER TABLE TABLE_PREFIXcarddav_group_user ROW_FORMAT=DYNAMIC;
ALTER TABLE TABLE_PREFIXcarddav_migrations ROW_FORMAT=DYNAMIC;
```

**Comment by groinwood** [comment]
I can confirm this indeed solved the issue. The version of MariaDB is 10.1.48. The rowformat of the tables was `COMPACT` and the default value for `innodb_large_prefix` in this version is `OFF`. After converting the rowformats of all tables to `DYNAMIC` and set the `innodb_large_prefix` to `ON`, the dbmigration succeeded. 

So special attention is needed when using an old version of MariaDB (<10.2.2) or MySQL (< 5.7.7).
I've configured these settings in my MariaDB server to be prepared for future upgrades and to avoid scenarios as described in this issue:
innodb_large_prefix=1
innodb_file_per_table=1
innodb_file_format=Barracuda
innodb_default_row_format = dynamic

**Comment by mstilkerich** [comment]
The same issue interestingly also came up in roundcube itself some days ago: roundcube/roundcubemail#8231

They addressed it by requiring the above MySQL configuration settings per the install documentation and changed their MySQL init scripts to set the row format to `DYNAMIC`. I think I will do the same, and add the above alter table statements to migration 12. They should do no harm in case the row format already is `DYNAMIC `.
