### ISSUE TITLE
Update to 1.5 causes sql error 

### ISSUE THREAD

**Issue by tribut** [mstilkerich/rcmcarddav#369]
When running the update from 1.4.11 to 1.5.1, I get the following error:

    Running update script at target...
    Executing database schema update.
    Updating database schema (2020020100)... [OK]
    Updating database schema (2020020101)... [FAILED]
    ERROR: Error in DDL upgrade 2020020101: [1834] Cannot delete rows from table which is parent in a foreign key constraint 'carddav_addressbooks_ibfk_1' of table 'carddav_addressbooks'                        
    All done.

Probably related to https://github.com/roundcube/roundcubemail/issues/7277 https://github.com/roundcube/roundcubemail/issues/8262

I don't notice any immediate problems with the installation though.

**Comment by mstilkerich** [comment]
Hello,

 I cannot address this in rcmcarddav, because it occurs in a roundcube schema migration and this migration only considers the tables of roundcube core. As [mentioned in roundcube issue 8262](https://github.com/roundcube/roundcubemail/issues/8262#issuecomment-953513866), you will have to fix the situation manually.

You can extend the roundcube script 2020020101.sql to drop the foreign key constraint in the carddav_addressbooks table in the beginning and add it again at the end of the script as the script already does for all its own tables.

This would look like the following (not tested myself):

Beginning:
```sql
ALTER TABLE `carddav_addressbooks` DROP FOREIGN KEY `carddav_addressbooks_ibfk_1`;
```

End:
```sql
ALTER TABLE `carddav_addressbooks` ADD CONSTRAINT `carddav_addressbooks_ibfk_1` FOREIGN KEY (user_id) REFERENCES TABLE_PREFIXusers(user_id) ON DELETE CASCADE ON UPDATE CASCADE;
```

Note I have no clue what roundcube does when a schema migration fails, i.e. if it will retry the migration again when you run the install script again, and if it carried out the subsequent schema migrations. At this point, you may be left with a broken roundcube schema, so I would not leave this as is.

**Comment by tribut** [comment]
Thanks for getting back to me.

It seems that Rouncube simply stops the upgrade at the failing file (further migrations are not applied, there is no rollback for the partially applied migration).

To solve this, I made the changes you recommended, manually re-added the constraints that the migration had already dropped and then re-ran the upgrade script.

Again, thanks a lot!

**Comment by mstilkerich** [comment]
Great if it works for you now, thanks for the feedback!
