### ISSUE TITLE
Empty password is sent in Authorization header

### ISSUE THREAD

**Issue by tomsommer** [mstilkerich/rcmcarddav#371]
I'm using `%p` in my config, but it seems an empty password is being sent in the Authorization header, here is a stack trace:

The username is correct (%u)

```
[07-Dec-2021 14:58:09 +0100]: <b5qnn06l> [5 ERR] Errors occurred during the refresh of addressbook 1541: Exception: Expected Multistatus HTTP request was not successful (401 Unauthorized): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.2.1</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>Username or password was incorrect</s:message>
</d:error>
 in ../vendor/mstilkerich/carddavclient/src/CardDavClient.php:478
Stack trace:
#0 ../vendor/mstilkerich/carddavclient/src/CardDavClient.php(494): MStilkerich\CardDavClient\CardDavClient::assertHttpStatus(Object(GuzzleHttp\Psr7\Response), 207, 207, 'Expected Multis...')
#1 ../vendor/mstilkerich/carddavclient/src/CardDavClient.php(424): MStilkerich\CardDavClient\CardDavClient::checkAndParseXMLMultistatus(Object(GuzzleHttp\Psr7\Response), 'MStilkerich\\Car...')
#2 ../vendor/mstilkerich/carddavclient/src/WebDavResource.php(142): MStilkerich\CardDavClient\CardDavClient->findProperties('https://dav.sim...', Array)
#3 ../vendor/mstilkerich/carddavclient/src/WebDavResource.php(127): MStilkerich\CardDavClient\WebDavResource->refreshProperties()
#4 ../vendor/mstilkerich/carddavclient/src/WebDavCollection.php(110): MStilkerich\CardDavClient\WebDavResource->getProperties()
#5 ../vendor/mstilkerich/carddavclient/src/WebDavCollection.php(58): MStilkerich\CardDavClient\WebDavCollection->supportsReport('{DAV:}sync-coll...')
#6 ../vendor/mstilkerich/carddavclient/src/Services/Sync.php(94): MStilkerich\CardDavClient\WebDavCollection->supportsSyncCollection()
#7 ../vendor/mstilkerich/carddavclient/src/Services/Sync.php(57): MStilkerich\CardDavClient\Services\Sync->synchronizeOneBatch(Object(MStilkerich\CardDavClient\AddressbookCollection), Object(MStilkerich\CardDavAddressbook4Roundcube\SyncHandlerRoundcube), Array, 'http://sabre.io...')
#8 ../plugins/carddav/src/Addressbook.php(1244): MStilkerich\CardDavClient\Services\Sync->synchronize(Object(MStilkerich\CardDavClient\AddressbookCollection), Object(MStilkerich\CardDavAddressbook4Roundcube\SyncHandlerRoundcube), Array, 'http://sabre.io...')
#9 ../plugins/carddav/carddav.php(1487): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->resync()
#10 ../plugins/carddav/carddav.php(430): carddav->resyncAddressbook(Object(MStilkerich\CardDavAddressbook4Roundcube\Addressbook))
#11 ../program/lib/Roundcube/rcube_plugin_api.php(513): carddav->getAddressbook(Array)
#12 ../program/include/rcmail.php(338): rcube_plugin_api->exec_hook('addressbook_get', Array)
#13 ../program/actions/contacts/photo.php(58): rcmail->get_address_book('carddav_1541')
#14 ../program/include/rcmail.php(275): rcmail_action_contacts_photo->run(Array)
#15 ../index.php(283): rcmail->action_handler()
#16 ../public_html/index.php(26): include('/var/www/roundc...')
#17 {main}

```

**Comment by mstilkerich** [comment]
Hello,

  have you verified that an Authorisation header with an empty password is sent? I'm asking because the log message you posted only shows that the authentication with the server failed.

Unfortunately you did not provide a lot of information on your setup, so I have to guess:
- The password decryption from the database fails. Not that the password is always fetched from the database, even if it is only a placeholder. Password decryption can fail if it is stored to the database encrypted and the decryption key changed. Most commonly, when using the default encrypted scheme, the IMAP password is used for encryption. If the IMAP password is changed, the CardDAV password needs to be stored again.
- The error message indicates that the addressbook discovery worked, which normally requires a successful authentication at the server. So did you change anything related to passwords since the successful discovery and now?
- When you change a configuration setting in a preset (e.g. password), it is only updated in the database if it is listed as a `fixed` setting of the preset. Otherwise setting is user configurable and the user would have to adapt it using the settings interface. `fixed` settings are updated upon login of the user. So in case you originally had the password stored inside the preset (just guessing) and now changed it to `%p`, this will only take effect when password is among the `fixed` fields, and then only upon logging into roundcube.
- Another reason why the password would be empty is if there is no IMAP password used for login, e.g. OAUTH2 or Kerberos authentication. But in this case `%p` obviously cannot be used.

If the above does not help, please provide more information:
- Which roundcube / rcmcarddav version are you using, how to you authenticate to roundcube?
- Did you change anything related to passwords (configuration or the passwords themselves, both IMAP and CardDAV) since the successful discovery?
- What does your `config.inc.php` look like?
- What does the database row in the `carddav_addressbooks` table contain for that addressbook?
- What does the HTTP log contain? To see the non-redacted content of the auth header, you need to comment out the call to `redactMessage()` in `src/RoundcubeLogger.php`. You can then base64 decode the content of the Authorization header to see if the password is in fact empty.

**Comment by mstilkerich** [comment]
There is no special case for the placeholder concerning storage in the database. The "%p" is stored in the database as the password, possibly encrypted according to the configured storage scheme.

The stored password will be updated if:
  - the `password` field is listed as a `fixed` property in the preset configuration
  - the user logs into roundcube (this is the time presets are processed)

This is described in detail in [ADMIN-SETTINGS.md](https://github.com/mstilkerich/rcmcarddav/blob/master/doc/ADMIN-SETTINGS.md)

**Comment by tomsommer** [comment]
I did base64 decode the Authentication header to check that the password is empty `foo@bar.com:`

I changed 'fixed' to 'username' and 'password', does not seem to help.

The error in the log is

```
[07-Dec-2021 21:29:57 +0100]: <ng738opm> [1 DBG] internalGet query: SELECT * FROM carddav_addressbooks WHERE ((`user_id` = '228104'))
[07-Dec-2021 21:29:57 +0100]: <g0ih11b8> [1 DBG] None of the available auth schemes worked
```

But if decryption fails, you are saying the IMAP password should still be used as fallback? (when %p is used in preset) I don't see that in the code, but maybe I didn't look hard enough.

**Comment by mstilkerich** [comment]
No if the decryption fails it will use an empty password. However, upon next login to roundcube the password in the database would be updated and afterwards decryption and hence authentication at the carddav server should work again.

If you want to do it manually, you can simply set the password to „%p“ in the database for all addressbooks that belong to that preset, like `UPDATE carddav_addressbooks set password='%p' WHERE presetname = 'key of the preset';`

**Comment by mstilkerich** [comment]
btw if you want to avoid these issues after a password change, you can consider changing the password store scheme to one that does not depend on the imap password.

**Comment by tomsommer** [comment]
Awesome. Thank you.

**Comment by mstilkerich** [comment]
I assume this is resolved for you.

**Comment by tomsommer** [comment]
Yes, ran the SQL query etc.
