### ISSUE TITLE
feature: set $config['collected_recipients'] and $config['collected_senders'] to carddav address books by default

### ISSUE THREAD

**Issue by chaos-prevails** [mstilkerich/rcmcarddav#383]
Hello,

I'm using latest RC1.5, and we have 2 default address books for all users:
1) Personal address book for each users (which should be used for collected recipients)
2) Staff address book unique for all users (which should be used for collected senders: Trusted senders)

By default, when using SQL address books, to use specific address books to collect recipients, or trust senders,  this is "solved" automatically by setting both parameters (collected_recipients, and collected_senders) to true.

Is there maybe a known workaround to have the same functionality when using carddav address books? Right now, I have to manually set both settings via the roundcube webinterface, and the change of setting shows up as "carddav_X" the roundcube parameter field (X being the ID in carddav_addressbooks).

1) I've already disabled all other address books as described here https://github.com/mstilkerich/rcmcarddav/issues/372
2) I would like to automatically point (at least) the "collect recipients", ideally also the "trusted senders" to the 2 different carddav address books

If there is no current workaround, what would it need for the carddav plugin to make something like this possible? I think it might be quite common to have those address books (one for staff members, e.g. read-only, and one personal ones to collect email addresses of outgoing email), and setting them by default saves additional config needs per user.

1) for (pre-configured) address books, new parameters like "collected_recipient_name" or "collected_senders_name" (specifying an identifier (or an array of identifiers) to find the address book name (or URL, or both) which should be used for collecting recipients/trusted senders (I think in many cases the name/URL of those address books would always be very similar containing words like "staff", "personell", "global" or "collected", or "personal" in it, or a specific fixed ID in the URL for one shared address book)
2) on roundcube side, the parameter collected_recipients, and collected_senders should accept something like "carddav" (update of the documentation)
3) Whenever a discovery of address books is done, and above roundcube parameters are set to "carddav", the carddav code would need to have a look at all discovered address books of the user, and their names/URLs, and set the roundcube parameter in the table users accordingly (e.g. just get the ID of the address book, and set carddav_X as you can currently do manually). 

Manual override would not be possible that way, but maybe that is an acceptable compromise? Otherwise it would need another value somewhere (also in users->parameters?). 

That way, no change of code on the roundcube side would be needed, right? Would that be something that is feasible?

**Comment by mstilkerich** [comment]
Hello,

  I think this should be possible without any change at the roundcube side, since plugins are able to override roundcube settings.

- rcmcarddav can set the roundcube options value like it already does for the autocomplete addressbooks
- The admin configure roundcube to hide the corresponding settings from the preferences panel:
```php
$config['dont_override'] = ['collected_recipients', 'collected_senders'];
```

However, I believe both addressbooks must be writeable (see [here](https://kolabian.wordpress.com/2020/09/26/collected-recipients-and-trusted-senders/)), roundcube will add to the "collected_senders" addressbook the senders of E-Mails where the user allows to download remote resources. Roundcube will also not offer a readonly carddav addressbook for manual configuration by the user in the corresponding preferences.

So I think the key issue here will be the selection mechanism on how to identify the corresponding addressbooks within a preset. I'm thinking in the direction of a pattern match (i.e. allowing placeholders like %u) for the name and URL, or even a regular expression match on those attributes. Questions are how to handle cases where there is no match or several matches possible. For no match, when not setting the option roundcube would resort to the default option configured by the admin. This could be the internal SQL addressbook or also disabling the feature. With several matches, we could either log an error an not set the option in roundcube (behaviour like when no match), or we could set the first (that means an arbitrary) match. But when doing this, we should be sure we choose the same match every time consistently, which might be difficult again (I'm thinking on doing this selection based on config.inc.php setting, without additional DB attributes to mark the addressbook).

**Comment by mstilkerich** [comment]
So I just tried what happens if I set a readonly carddav addressbook from the plugin for roundcube (i.e. an addressbook, that would not be offered by roundcube for the user to select).

In this case, roundcube will nevertheless attempt to store a contact to the addressbook. rcmcarddav will also not check the readonly property (it's really just something that affects roundcube's frontend) and store to the server. That means in case the addressbook is readonly per server-side access permissions, the user will be shown an error message by roundcube that the contact could not be added, otherwise the contact will be created. I therefore think it is better to not allow rcmcarddav to set addressbooks from readonly presets for these two settings, as it violates roundcube's preconditions for these settings.

**Comment by chaos-prevails** [comment]
thanks for all the info. Yes, I agree, it wouldn't make sense to choose a readonly address book (I didn't know the process to add trusted senders is "automatic" by allowing remote content). 

I think in practical terms, having more than one match for a pattern could be easily prevented by the admin by using the UUID, or full URL (with %u) of the address book for the pattern. Optionally the carddav settings could be hidden, so if the UUID is something readable (e.g. in sogo the default address book is called "personal"), the user could not add additional address books, so there cannot be any interference.

I think the possibility of stating the full URL with a login-dependent sub-string would be the most fail-proof approach, as this should be unique, and users could still be allowed to add other address books.

**Comment by mstilkerich** [comment]
Hello,

  I have pushed a prototypic implementation to the branch issue_383_collectedsenders_receivers. Does it satisfy your use case?

Configuration looks like this:
```php
$prefs['_GLOBAL']['collected_recipients'] = [
    'preset'  => 'iCloud',
    'matchname' => '/card/i',
];
$prefs['_GLOBAL']['collected_senders'] = [
    'preset'  => 'iCloud',
    'matchurl' => '#https://p57-contacts.icloud.com:443/\d+/carddavhome/card/#',
];
```

If both `matchname` and `matchurl` are given, both need to match. There must be exactly one match inside the preset, and the preset must not be readonly. Both must be PHP regular expressions. Same placeholders as inside an URL (e.g. `%u`) are possible inside the regular expressions.

**Comment by chaos-prevails** [comment]
Hello,

thanks, the automatic set is working quite well! both collected_senders, and collected_recipients are set, and matchname worked perfectly!

However, with matchurl I had troubles. I only got a match if the string did only contain alphanumeric characters, and hyphens. As soon as I used specific special characters (e.g. @, _ or /) (escaped, or not), I didn't get a match, but instead: 

`[5 ERR] Cannot set special addressbook collected_senders, there are 0 candidates (need: 1)`

one example which did work:
```
$prefs['_GLOBAL']['collected_senders'] = [
    'preset'  => 'SOGo_autodiscovery',
#    'matchname' => '/Staff/i', <-- worked before being commented
    'matchurl' => '/Some-UID-X-1234/', #<-- this part of a URL worked as well 
];
```

These examples however didn't work
```
$prefs['_GLOBAL']['collected_senders'] = [
    'preset'  => 'SOGo_autodiscovery',
    'matchurl' => '/firstname\_lastname/',  # <-- as soon as `something_` is used, there is no match, however '/\_lastname/' worked
#    'matchurl' => '/https:\/\/mail.mydomain\.net\/SOGo\/dav\/firstname\_lastname\@mydomain\.net\/Contacts\/SOME-UID-X-1234\//', #<-- also with hashtag at either end, there is no match.
'matchurl' => '#https://mail.mydomain.net/SOGo/dav/lastname_firstname@mydomain.net/Contacts/SOME-UID-X-1234/#', #<-- no match either
#    'matchurl' => '/Contacts\/SOME-UID-X-1234/', #<-- no match
#    'matchurl' => '/Contacts/SOME-UID-X-1234/', #<-- no match either
#    'matchurl' => '/Contacts/SOME-UID-X-1234/', #<-- no match either
];
```

I use SOGo as backend, and URLs have the following structure:
`https://mail.mydomain.net/SOGo/dav/user@mydomain.net/Contacts/UID-ID-X/`

so there are evidently slashes, but also @ and '-'.

Additionally, even if trusted sender was set, and a sender was in this address book, an email from this sender did not automatically show remote content. However, resetting everything to SQL, disabling carddav plugin, setting trusted senders to personal, adding my email to this address book, it still didn't show remote content automatically. So I guess I need another roundcube setting for that.

Regarding collecting recipients, if I sent an email to a new recipient, the recipient email was added to the collected_recipients Carddav book, so that worked perfectly.
