### ISSUE TITLE
Release tarball with incompatible guzzle dependency to roundcube 1.6

### ISSUE THREAD

**Issue by Offerel** [mstilkerich/rcmcarddav#385]
It seems that the plugin isn't working yet with Roundcube 1.6 RC. No info is written to the logfiles. Can you please check and provide a fix or at least workaround?

**Comment by Offerel** [comment]
I have manually inserted GuzzleHttp 7.4.4 into the proper directory. This solved the issue for me. At least this seems to be a workaround, if some other has the same issue. So it should be a relative easy fix for Roundcube 1.6 final

**Comment by mstilkerich** [comment]
Hello, I guess you use the tarball release of rcmcarddav and did not install using composer? The tarball comes with a v6 guzzle because that is what roundcube 1.5 requires. This now clashes with the v7 guzzle in roundcube 1.6. I have described the possibility of such conflicts when using the tarball in the INSTALL.md. This is why install via composer is highly recommended.

**Comment by mstilkerich** [comment]
There is no real fix to this issue other than using composer to avoid duplicate and likely different versions of dependencies that may cause all kinds of weird issues, including more subtle ones than the fatal error in the situation at hand.

If I include guzzle 7 in the tarball, it will cause incompatibility to roundcube 1.5. So the only workaround I see is having two release tarballs. As I said, there may be issues with other dependencies as well that are not known. IMO not being the biggest fan of composer is not a good reason to go for a possibly broken installation, but that’s your choice.
