### ISSUE TITLE
SOGo address book, discovery_url not working

### ISSUE THREAD

**Issue by mahmoudqawssmi** [mstilkerich/rcmcarddav#402]
I am trying to connect to SOGo personal address book on ubuntu 20.04/php 7.4/roundcube 1.6.0/rcmcarddav 4.4.3:

$prefs['Personal'] = [
    'accountname'  =>  'Personal',
    'username'     =>  '%u',
    'password'     =>  '%p',
	'discovery_url' =>  'https://mail.mydomain.com/SOGo/dav/%u/Contacts/personal/',
    'name'         => '%a (%N)',
    'active'       =>  true,
    'readonly'     =>  false,
    'refresh_time' => '02:00:00',
    'fixed'        =>  ['discovery_url', 'username', 'password'],
    'hide'         =>  false,
];

I am getting this error:
roundcube: <rit0djol> [5 ERR] Error adding addressbook from preset Personal: The account's discovery URI must contain a hostname (got: )

The only way to get address book is to add/replace discovery_url with url:
'discovery_url' =>  'https://mail.mydomain.com/SOGo/dav/%u/Contacts/personal/',     <- this doesn't work, and gives the error above
'url' =>  'https://mail.mydomain.com/SOGo/dav/%u/Contacts/personal/', <- this works

using url, all books will be discovered, no matter what is in the link:
'url' =>  'https://mail.mydomain.com/SOGo/dav/%u/Contacts/personal/',
'url' =>  'https://mail.mydomain.com',

both 'url' above gives same results: "%a (%N) (Personal Address Book)" and "%a (%N) (Global Address Book)"

I wonder what could be wrong

**Comment by mstilkerich** [comment]
Hello, if you are in fact using v4.4.3, it cannot work with the given preset as it uses the new configuration options for the upcoming v5. Please see config.inc.php.dist file and doc/ADMIN_SETTINGS.MD that come with your release for the proper configuration. Briefly said, as you already discovered the url for discovery must be given with url, the name templates are not available yet in v4.

That all addressbooks are being discovered is normal and expected behavior.

**Comment by mahmoudqawssmi** [comment]
well, that explain it all, thanks alot, I will test on V5.

**Comment by mstilkerich** [comment]
v5 is still in development, so expect bugs. However, if you’re willing to try and encounter any issues, I appreciate your issue reports 🙂

I assume this issue is resolved and will close it.
