### ISSUE TITLE
Composer Update

### ISSUE THREAD

**Issue by WebCodePoet** [mstilkerich/rcmcarddav#413]
Just a hint, not really an issue. By running Composer Update:

Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.

**Comment by mstilkerich** [comment]
Hello,

  I am not seeing this message. This is not a direct requirement of rcmcarddav.

- What roundcube version do you use and what does your roundcube/carddav dependency look like?
- What does `composer depends webmozart/path-util` output?

It may also be caused by another factor in your environment, for example an old php version preventing the upgrade of the package that depends on webmozart/path-util to a newer version that does not depend on it (just a guess).

**Comment by WebCodePoet** [comment]
Hey, at first I run the command again to show you the full output:

plugins/carddav# composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating autoload files
44 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found

Than I run the command as you wished:

plugins/carddav# composer depends webmozart/path-util
vimeo/psalm 4.30.0 requires webmozart/path-util (^2.3)

And this is definied in your composer.json:

    "require-dev": {
        "vimeo/psalm": "^4",

**Comment by mstilkerich** [comment]
Hello,

  ok, rcmcarddav master has moved on to psalm 5 and it is fixed there. vimeo/psalm#7826

Btw if you don‘t intend to do development then I‘d suggest running composer with `—no-dev` to avoid installing the development dependencies of all the packages.

**Comment by mstilkerich** [comment]
And also you should run composer in the roundcube root dir, not inside the carddav plugin dir. See INSTALL.MD
