### ISSUE TITLE
Auto-created vCards on Reply have empty N property

### ISSUE THREAD

**Issue by dilyanpalauzov** [mstilkerich/rcmcarddav#447]
Apparently when I click on Reply in Roundcube, a vCard for the new contact is created over CardDAV.  It has in the `FN:` field the sender of the initial email.  But the `N:` property contains `;;;;`, so it is empty.  When using Evolution to sort the contacts per First or Last name, it uses the `N` property for this.

When creating vCards, please set also data in the N property:
* if the sender is called (has display-name in the From: header) “X Y” then X is the first, Y the last name
* if the sender is called "X, Y" then Y is the first, X the last name
* if the sender is called "X Y Z" then by default X is the first, Y the second and Z the last name

These are reasonable defaults.  They will not work in 100% of the cases correctly, but are best try, and will be an improvement compared to the current situation.

**Comment by mstilkerich** [comment]
This is intentional. It is perfectly fine to have a vcard with empty N property and it will commonly happen for vcards that represent a company and not an individual. Also in the roundcube contacts edit mask it is possible to save a contact with leaving firstname and surname attributes empty.

RCMCardDAV just receives a data object from roundcube lacking the firstname and surname property with a request to save it. We cannot know if this is intentional (e.g. the user chose to save a contact without firstname / surname, e.g. a company contact) or whether it is because of roundcube attempting to automatically create a contact from the information present in an email (which is an email address and a formatted name). Therefore this magic will produce unintended results for users intentionally saving a contact without firstname/lastname, and semantically wrong information in case the added contact is a company and not an individual.

I actually thought about this when I created the data converter but decided to better have no magic than magic that produces unintended / wrong results in some cases.
