### ISSUE TITLE
Table carddav_accounts was not created and error during migration

### ISSUE THREAD

**Issue by Bieri71** [mstilkerich/rcmcarddav#450]
Roundcube version: **1.6.2**
PHP 8.2.8 (cli)

After the first installation, I had the following error.
`Database::get (SELECT * FROM MY_PREFIX_carddav_accounts WHERE ((`user_id` = '34'))) ERROR: [1146] Table 'MY_PREFIX_carddav_accounts' doesn't exist`

I modified the file to create the missing table
`plugins/carddav/dbmigrations/INIT-currentschema`

Now I wanted to install the plugin again and have an error during the reinstallation cardev with composer
`failed: [1050] Table 'MY_PREFIX_carddav_migrations' already exists`
in `plugins/carddav/dbmigrations/0000-dbinit/`

```CREATE TABLE TABLE_PREFIXcarddav_migrations```
would be better
`CREATE TABLE IF NOT EXISTS TABLE_PREFIXcarddav_migrations`

how could i get an update from cardev

**Comment by mstilkerich** [comment]
The tables are created on first login. These DB scripts are not supposed to be manually executed because the TABLE_PREFIX must be replaced by the one configured in the roundcube configuration. The second error you get is caused by your manual creation of the table. What you see is rcmcarddav trying to create the tables and finding they are already there.

* Please delete the tables you created manually from the database.
* Please read the install instructions: https://github.com/mstilkerich/rcmcarddav/blob/master/doc/INSTALL.md
* Log out of roundcube. Login again. The tables should now be created.
