### ISSUE TITLE
SQL drop files

### ISSUE THREAD

**Issue by ErikBasalt** [mstilkerich/rcmcarddav#69]
To start from scratch (or remove rcmcarddav from the system permanently), it would be handy having an SQL script to delete all CardDAV database tables. The "postgres.sql" script could look something like this:

DROP TABLE IF EXISTS carddav_group_user;

DROP TABLE IF EXISTS carddav_groups;
DROP SEQUENCE IF EXISTS carddav_groups_seq;

DROP TABLE IF EXISTS carddav_xsubtypes;
DROP SEQUENCE IF EXISTS carddav_xsubtypes_seq;

DROP INDEX IF EXISTS carddav_contacts_abook_id_idx;
DROP TABLE IF EXISTS carddav_contacts;
DROP SEQUENCE IF EXISTS carddav_contacts_seq;

DROP TABLE IF EXISTS carddav_addressbooks;
DROP SEQUENCE IF EXISTS carddav_addressbooks_seq;

DROP TABLE IF EXISTS carddav_migrations;
DROP SEQUENCE IF EXISTS carddav_migrations_seq;

I would suggest putting the scripts in new folder "dbdrop".

**Comment by mstilkerich** [comment]
Added a script `scripts/dropdb.php` that can be used. I used a PHP script because it can access the roundcube configuration and properly handle the table prefix if configured in roundcube, plus it gets the database connection info from the roundcube config as well.

Also added uninstallation instructions to `INSTALL.md`.
